# Generated by Django 2.1.7 on 2019-02-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='crated_date',
            new_name='created_date',
        ),
    ]
